name: 💡 機能追加・改善要望
description: 新しい機能の提案や改善要望はこちら
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ご提案ありがとうございます。
        開発チームのリソース調整のため、全ての要望に即座に応えられない場合がありますが、今後の重要な参考とさせていただきます。

  - type: textarea
    id: problem
    attributes:
      label: 解決したい課題・背景
      description: 現在、どのような業務や操作で困っていますか？（Why）
      placeholder: 例：毎月末の集計作業で、手動で計算するのが大変でミスが起きやすい
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: 要望の内容
      description: 具体的にどのような機能が欲しいですか？（What）
      placeholder: 例：集計画面に「CSVエクスポート」ボタンを追加してほしい
    validations:
      required: true

  - type: input
    id: deadline
    attributes:
      label: 希望納期（ある場合）
      description: 特定のイベントや業務スケジュールに合わせて必要な場合は日付を記入してください。
      placeholder: 例：202X年X月X日のリリースに合わせて

  - type: textarea
    id: alternatives
    attributes:
      label: 代替案・補足
      description: 今はどうやって対応していますか？その他参考情報があれば。
